app:
  version: @project.version@
spring:
  datasource:
    url: jdbc:h2:/tmp/codechallenge;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.josemiguel.codechallenge.infrastructure.naming.CodechallengeNamingStrategy
  cloud:
    function:
      definition: doSomething
  batch:
    jdbc:
      initialize-schema: always
management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /management
      exposure:
        include: 
          - "*"
  endpoint:
    health:
      show-details: always
      
kafka:
  username: josemi
  password: 525700
  hosts:
    - josemi.com
    - jalex.com
    
---
spring:
  config:
    activate:
      on-profile:
      - localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: fenix000
      

      