app:
  version: @project.version@
server:
  shutdown: graceful
spring:
  datasource:
    url: jdbc:h2:mem:codechallenge
    username: postgres
    password: fenix000
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    function:
      definition: doSomething, doSomething2
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 50s
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info 
        - metrics
        - prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: codeChallenge, readinessState
        
weather:
  url: https://api.openweathermap.org
  apiKey: 22073e0662677fdf6684f86fb4d470bf
  
 
      