spring:
  datasource:
    url: jdbc:h2:mem:codechallenge;;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: create-drop
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info 
  endpoint:
    health:
      show-details: always
