app:
  version: @project.version@
spring:
  datasource:
    url: jdbc:h2:/tmp/db;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    function:
      definition: doSomething, doSomething2
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info 
        - metrics
        - prometheus
  endpoint:
    health:
      show-details: always

      