app:
  version: @project.version@
server:
  shutdown: graceful
spring:
  datasource:
    url: jdbc:h2:mem:codechallenge
    username: postgres
    password: fenix000
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    function:
      definition: doSomething, doSomething2
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 50s
  rsocket:
    server:
      port: 7000
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info 
        - metrics
        - prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: codeChallenge, readinessState
        
weather:
  url: https://api.openweathermap.org
  apiKey: 22073e0662677fdf6684f86fb4d470bf
  
logging:
  level:
    org.springframework.web.socket: DEBUG
    
#amqphub:
#  amqp10jms:
#    remote-url: amqp://localhost:5672
#    username: jmbesada
#    password: fenix000
#    pool:
#      enabled: false
#      maxConnections: 10
  
 
      