spring:
  datasource:
    url: jdbc:h2:mem:codechallenge;;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: create-drop
      
server:
  servlet:
    session:
      cookie:
        same-site: Strict
