name: Deployment
on: 
  - workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-kubectl
        uses: steebchen/kubectl@v2.1.1
        with: 
          config: ${{secrets.KUBE_CONFIG_DATA}}
          command: kubectl get pods